port: 7890
socks-port: 7891
mixed-port: 7893
redir-port: 7892
tproxy-port: 7895
geodata-mode: true
geodata-loader: memconservative
tcp-concurrent: true
unified-delay: true
enable-process: true
inbound-tfo: false
allow-lan: true
bind-address: "*"
mode: rule
log-level: silent
ipv6: true
external-controller: 0.0.0.0:9090
external-ui: "/usr/share/openclash/ui"
secret: ""
interface-name: "wwan0"
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  sniffing:
    - tls
    - http
  force-domain:
    - "+.netflix.com"
    - "+.nflxvideo.net"
    - "+.amazonaws.com"
    - "+.media.dssott.com"
  skip-domain:
    - "+.apple.com"
    - Mijia Cloud
    - "+.jd.com"
  port-whitelist:
    - 443
    - 80
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - any:53
  auto-route: false
  auto-detect-interface: false
dns:
  enable: true
  device: Meta
  listen: 0.0.0.0:1053
  default-nameserver:
    - 1.0.0.1
    - 1.1.1.1
    - 8.8.8.8
    - 8.8.4.4
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  prefer-h3: false
  nameserver:
    - 1.0.0.1
    - 1.1.1.1
    - https://1dot1dot1dot1.cloudflare-dns.com/dns-query
    - 8.8.8.8
    - 8.8.4.4
    - https://dns.google/dns-query
  fallback:
    - 1.0.0.1
    - 1.1.1.1
    - https://1dot1dot1dot1.cloudflare-dns.com/dns-query
    - 8.8.8.8
    - 8.8.4.4
    - https://dns.google/dns-query
  fallback-filter:
    geoip: false
    geoip-code: 
      #- ID
    geosite:
      #- rule-indo
    ipcidr:
      - 240.0.0.0/4
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"
      - "*.ruangguru.com"
      - "space.byu.id"
  ipv6: true
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time-ios.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - "+.pool.ntp.org"
    - time1.cloud.tencent.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - "+.srv.nintendo.net"
    - "*.n.n.srv.nintendo.net"
    - "+.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - "+.battlenet.com.cn"
    - "+.wotgame.cn"
    - "+.wggames.cn"
    - "+.wowsgame.cn"
    - "+.wargaming.net"
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"
    - heartbeat.belkin.com
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - lens.l.google.com
    - stun.l.google.com
    - "+.nflxvideo.net"
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
    - "*.ff14.sdo.com"
    - ff.dorado.sdo.com
    - "*.mcdn.bilivideo.cn"
    - "+.media.dssott.com"
    - shark007.net
    - "*.ruangguru.com"
    - "space.byu.id"
geox-url:
  mmdb: "https://cdn.jsdelivr.net/gh/Dreamcro/maxmind-geoip@release/Country.mmdb"
  geoip: "https://github.com/malikshi/v2ray-rules-dat/raw/release/geoip.dat"
  geosite: "https://github.com/malikshi/v2ray-rules-dat/raw/release/geosite.dat"
proxies:
proxy-providers:
  ACCVMESS:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/degidevops/clash-account/main/vmess.yaml
    path: "./proxy_provider/vmess.yaml"
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 15
      #timeout: 1
  ACCVLESS:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/degidevops/clash-account/main/vless.yaml
    path: "./proxy_provider/vless.yaml"
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 15
      #timeout: 1
  ACCTROJAN:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/degidevops/clash-account/main/trojan.yaml
    path: "./proxy_provider/trojan.yaml"
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 15
      #timeout: 1
  ACCTROJAN-G:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/degidevops/clash-account/main/trojan-game.yaml
    path: "./proxy_provider/trojan-game.yaml"
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 15
      #timeout: 1
  ACCVLESS-G:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/degidevops/clash-account/main/vless-game.yaml
    path: "./proxy_provider/vless-game.yaml"
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 15
      #timeout: 1
proxy-groups:
  - name: G-BEST
    type: url-test
    proxies:
      - TVLESS-G
      - TTROJAN-G
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    disable-udp: false
  - name: G-FALL
    type: fallback
    proxies:
      - TVLESS-G
      - TTROJAN-G
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    disable-udp: false
  - name: BEST
    type: fallback
    proxies:
      - TVLESS
      - TTROJAN
      - TVMESS
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    disable-udp: false
  - name: LB
    type: load-balance
    strategy: consistent-hashing
    proxies:
      - ACCVLESS
      - ACCTROJAN
      - ACCVMESS
    url: http://www.gstatic.com/generate_204
    interval: 60
    disable-udp: false
  - name: Route GAME
    type: fallback
    proxies:
      - G-BEST
      - G-FALL
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    #timeout: 1
    disable-udp: false
  - name: TrafficPortGames
    type: select
    proxies:
      - Route GAME
    use:
      - ACCTROJAN-G
      - ACCVLESS-G
  - name: TrafficGaming
    type: select
    proxies:
      - Route GAME
    use:
      - ACCTROJAN-G
      - ACCVLESS-G
  - name: TrafficNSFW
    type: select
    proxies:
      - REJECT
      - TrafficUmum
  - name: TrafficUmum
    type: fallback
    proxies:
      - LB
      - BEST
    url: http://www.gstatic.com/generate_204
    interval: 60
  - name: TVMESS
    type: url-test
    use:
      - ACCVMESS
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
  - name: TVLESS
    type: url-test
    use:
      - ACCVLESS
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
  - name: TTROJAN
    type: url-test
    use:
      - ACCTROJAN
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
  - name: TVLESS-G
    type: url-test
    use:
      - ACCVLESS-G
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
  - name: TTROJAN-G
    type: url-test
    use:
      - ACCTROJAN-G
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
rules:
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- RULE-SET,rule_lancidr,DIRECT,no-resolve
- RULE-SET,rule_falsepositive,TrafficUmum
- RULE-SET,rule_porn,TrafficNSFW
- RULE-SET,rule_nsfw,TrafficNSFW
- RULE-SET,rule_portgames,TrafficPortGames
- RULE-SET,rule_Gaming,TrafficGaming
- RULE-SET,rule_games,TrafficGaming
- NOT,((RULE-SET,rule_umum)),TrafficPortGames
- RULE-SET,rule_umum,TrafficUmum
  #- MATCH,GLOBAL
rule-providers:
  rule_umum:
    type: http
    behavior: classical
    path: "./rule_provider/rule_umum.yaml"
    url: https://raw.githubusercontent.com/degidevops/clash-config/main/rule_provider/rule_umum.yaml
    interval: 86400
  rule_portgames:
    type: http
    behavior: classical
    path: "./rule_provider/rule_portgames.yaml"
    url: https://raw.githubusercontent.com/degidevops/clash-config/main/rule_provider/rule_portgames.yaml
    interval: 86400
  rule_Gaming:
    type: http
    behavior: classical
    path: "./rule_provider/rule_gaming.yaml"
    url: https://raw.githubusercontent.com/degidevops/clash-config/main/rule_provider/rule_gaming.yaml
    interval: 86400
  rule_falsepositive:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/degidevops/clash-config/main/rule_provider/rule_falsepositive.yaml
    path: "./rule_provider/rule_falsepositive.yaml"
    interval: 86400
  rule_porn:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/degidevops/clash-config/main/rule_provider/rule_porn.yaml
    path: "./rule_provider/rule_porn.yaml"
    interval: 86400
  rule_nsfw:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/degidevops/clash-config/main/rule_provider/rule_nsfw.yaml
    path: "./rule_provider/rule_nsfw.yaml"
    interval: 43200
  rule_lancidr:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/degidevops/clash-config/main/rule_provider/rule_lancidr.yaml
    path: "./rule_provider/rule_lancidr.yaml"
    interval: 86400
  rule_games:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/degidevops/clash-config/main/rule_provider/rule_games.yaml
    path: "./rule_provider/rule_games.yaml"
    interval: 86400
hosts:
  "*.ruangguru.com": 104.18.2.2
  "space.byu.id": 162.159.128.79
